[package]
name = "r_1_sky"
version = "0.1.0"
authors = ["zhylmzr <zhylmzr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "../utils" }